import { faCopy, faPrint, faVolumeUp, faChalkboard, faBusinessTime, faMobileAlt, faDesktop, faEdit, faProjectDiagram, faUsers, faCameraRetro, faClipboardList, faLayerGroup, faBuilding, faCogs, faClock, faWheelchair, faGlobe, faRing, faConciergeBell, faBell, faScissors, faFemale, faPills, faPlug, faBolt, faFire, faCar, faGlassMartiniAlt, faCouch, faBus, faWifi, faParking, faChild, faBabyCarriage, faMusic, faBed, faCoffee, faSuitcase, faFilm, faPaw, faChalkboardTeacher, faMoneyBillAlt, faDoorOpen, faUserMd, faShuttleVan, faTaxi, faUtensils, faTshirt, faCocktail, faSnowflake, faSwimmingPool, faSpa, faSmoking, faGamepad, faFutbol, faMartiniGlassCitrus } from "@fortawesome/free-solid-svg-icons";

export const AMENITIES = [
    { id: 'PHOTOCOPIER', code: 'BUS.2', name: 'Fotocopiadora', icon: faCopy },
    { id: 'PRINTER', code: 'BUS.28', name: 'Impresora', icon: faPrint },
    { id: 'AUDIO-VIS_EQT', code: 'BUS.37', name: 'Equipo Audiovisual', icon: faVolumeUp },
    { id: 'WHITE/BLACKBOARD', code: 'BUS.38', name: 'Pizarra blanca/negra', icon: faChalkboard },
    { id: 'BUSINESS_CENTER', code: 'BUS.39', name: 'Centro de negocios', icon: faBusinessTime },
    { id: 'CELLULAR_PHONE_RENTAL', code: 'BUS.40', name: 'Alquiler de teléfonos móviles', icon: faMobileAlt },
    { id: 'COMPUTER_RENTAL', code: 'BUS.41', name: 'Alquiler de computadoras', icon: faDesktop },
    { id: 'EXECUTIVE_DESK', code: 'BUS.42', name: 'Escritorio ejecutivo', icon: faEdit },
    { id: 'LCD/PROJECTOR', code: 'BUS.45', name: 'Proyector LCD', icon: faProjectDiagram },
    { id: 'MEETING_ROOMS', code: 'BUS.46', name: 'Salas de reuniones', icon: faUsers },
    { id: 'OVERHEAD_PROJECTOR', code: 'BUS.48', name: 'Proyector de diapositivas', icon: faCameraRetro },
    { id: 'SECRETARIAL_SERVICES', code: 'BUS.49', name: 'Servicios de secretaría', icon: faClipboardList },
    { id: 'CONFERENCE_SUITE', code: 'BUS.94', name: 'Suite de conferencias', icon: faLayerGroup },
    { id: 'CONVENTION_CTR', code: 'BUS.95', name: 'Centro de convenciones', icon: faBuilding },
    { id: 'MEETING_FACILITIES', code: 'BUS.96', name: 'Instalaciones para reuniones', icon: faCogs },
    { id: '24_HOUR_FRONT_DESK', code: 'HAC.1', name: 'Recepción 24 horas', icon: faClock },
    { id: 'DISABLED_FACILITIES', code: 'HAC.101', name: 'Instalaciones para discapacitados', icon: faWheelchair },
    { id: 'MULTILINGUAL_STAFF', code: 'HAC.103', name: 'Personal multilingüe', icon: faGlobe },
    { id: 'WEDDING_SERVICES', code: 'HAC.104', name: 'Servicios para bodas', icon: faRing },
    { id: 'BANQUETING_FACILITIES', code: 'HAC.105', name: 'Instalaciones para banquetes', icon: faConciergeBell },
    { id: 'PORTER/BELLBOY', code: 'HAC.106', name: 'Portero/Botones', icon: faBell },
    { id: 'BEAUTY_PARLOUR', code: 'HAC.107', name: 'Salón de belleza', icon: faScissors },
    { id: 'WOMENS_GST_RMS', code: 'HAC.110', name: 'Salas de mujeres', icon: faFemale },
    { id: 'PHARMACY', code: 'HAC.111', name: 'Farmacia', icon: faPills },
    { id: '120_AC', code: 'HAC.113', name: '120V AC', icon: faPlug },
    { id: '120_DC', code: 'HAC.114', name: '120V DC', icon: faBolt },
    { id: '220_AC', code: 'HAC.115', name: '220V AC', icon: faPlug },
    { id: '220_DC', code: 'HAC.117', name: '220V DC', icon: faBolt },
    { id: 'BARBECUE', code: 'HAC.118', name: 'Barbacoa', icon: faFire },
    { id: 'BUTLER_SERVICE', code: 'HAC.136', name: 'Servicio de mayordomo', icon: faConciergeBell },
    { id: 'CAR_RENTAL', code: 'HAC.15', name: 'Alquiler de coches', icon: faCar },
    { id: 'CASINO', code: 'HAC.16', name: 'Casino', icon: faMoneyBillAlt },
    { id: 'BAR', code: 'HAC.165', name: 'Bar', icon: faGlassMartiniAlt },
    { id: 'LOUNGE', code: 'HAC.165', name: 'Salón', icon: faCouch },
    { id: 'TRANSPORTATION', code: 'HAC.172', name: 'Transporte', icon: faBus },
    { id: 'WIFI', code: 'HAC.178', name: 'Wi-Fi', icon: faWifi },
    { id: 'WIRELESS_CONNECTIVITY', code: 'HAC.179', name: 'Conectividad inalámbrica', icon: faWifi },
    { id: 'BALLROOM', code: 'HAC.191', name: 'Salón de baile', icon: faUsers },
    { id: 'BUS_PARKING', code: 'HAC.192', name: 'Estacionamiento para autobuses', icon: faParking },
    { id: 'CHILDRENS_PLAY_AREA', code: 'HAC.193', name: 'Área de juegos para niños', icon: faChild },
    { id: 'NURSERY', code: 'HAC.194', name: 'Guardería', icon: faBabyCarriage },
    { id: 'DISCO', code: 'HAC.195', name: 'Discoteca', icon: faMusic },
    { id: '24_HOUR_ROOM_SERVICE', code: 'HAC.2', name: 'Servicio a la habitación 24 horas', icon: faBed },
    { id: 'COFFEE_SHOP', code: 'HAC.20', name: 'Cafetería', icon: faCoffee },
    { id: 'BAGGAGE_STORAGE', code: 'HAC.201', name: 'Almacenamiento de equipaje', icon: faSuitcase },
    { id: 'NO_KID_ALLOWED', code: 'HAC.217', name: 'No se permiten niños', icon: faChild },
    { id: 'KIDS_WELCOME', code: 'HAC.218', name: 'Niños bienvenidos', icon: faChild },
    { id: 'COURTESY_CAR', code: 'HAC.219', name: 'Coche de cortesía', icon: faCar },
    { id: 'CONCIERGE', code: 'HAC.22', name: 'Conserje', icon: faConciergeBell },
    { id: 'NO_PORN_FILMS', code: 'HAC.220', name: 'No se permiten películas pornográficas', icon: faFilm },
    { id: 'INT_HOTSPOTS', code: 'HAC.221', name: 'Puntos de acceso internacionales', icon: faWifi },
    { id: 'FREE_INTERNET', code: 'HAC.222', name: 'Internet gratuito', icon: faWifi },
    { id: 'INTERNET_SERVICES', code: 'HAC.223', name: 'Servicios de Internet', icon: faWifi },
    { id: 'PETS_ALLOWED', code: 'HAC.224', name: 'Se admiten mascotas', icon: faPaw },
    { id: 'FREE_BREAKFAST', code: 'HAC.227', name: 'Desayuno gratuito', icon: faCoffee },
    { id: 'CONFERENCE_FACILITIES', code: 'HAC.24', name: 'Instalaciones para conferencias', icon: faChalkboardTeacher },
    { id: 'HI_INTERNET', code: 'HAC.259', name: 'Internet de alta velocidad', icon: faWifi },
    { id: 'EXCHANGE_FAC', code: 'HAC.26', name: 'Instalaciones de cambio', icon: faMoneyBillAlt },
    { id: 'LOBBY', code: 'HAC.276', name: 'Lobby', icon: faDoorOpen },
    { id: 'DOCTOR_ON_CALL', code: 'HAC.28', name: 'Médico de guardia', icon: faUserMd },
    { id: '24H_COFFEE_SHOP', code: 'HAC.281', name: 'Cafetería 24 horas', icon: faCoffee },
    { id: 'AIRPORT_SHUTTLE', code: 'HAC.282', name: 'Transporte al aeropuerto', icon: faShuttleVan },
    { id: 'LUGGAGE_SERVICE', code: 'HAC.283', name: 'Servicio de equipaje', icon: faSuitcase },
    { id: 'PIANO_BAR', code: 'HAC.284', name: 'Bar de piano', icon: faMartiniGlassCitrus },
    { id: 'TAXI', code: 'HAC.285', name: 'Taxi', icon: faTaxi },
    { id: 'MEETING_SPACE', code: 'HAC.286', name: 'Espacio para reuniones', icon: faChalkboardTeacher },
    { id: 'ROOM_FOR_DISABLED', code: 'HAC.288', name: 'Habitación para discapacitados', icon: faWheelchair },
    { id: 'FOOD_SERVICES', code: 'HAC.289', name: 'Servicios de comida', icon: faUtensils },
    { id: 'TRAVELERS_LAUNDRY', code: 'HAC.29', name: 'Lavandería para viajeros', icon: faTshirt },
    { id: 'LOUNGE_BAR', code: 'HAC.290', name: 'Bar en salón', icon: faCocktail },
    { id: 'CONVENTION_ROOM', code: 'HAC.292', name: 'Salón para convenciones', icon: faBuilding },
    { id: 'EXCHANGE', code: 'HAC.294', name: 'Cambio', icon: faMoneyBillAlt },
    { id: 'AIRPORT_SHUTTLE', code: 'HAC.298', name: 'Shuttle al aeropuerto', icon: faShuttleVan },
    { id: 'ICE_MAKER', code: 'HAC.3', name: 'Fabricador de hielo', icon: faSnowflake },
    { id: 'POOL', code: 'HAC.30', name: 'Piscina', icon: faSwimmingPool },
    { id: 'SAUNA', code: 'HAC.33', name: 'Sauna', icon: faSpa },
    { id: 'SMOKING_AREA', code: 'HAC.34', name: 'Área para fumadores', icon: faSmoking },
    { id: 'GAME_ROOM', code: 'HAC.35', name: 'Sala de juegos', icon: faGamepad },
    { id: 'AMUSEMENT_PARK', code: 'HAC.38', name: 'Parque de diversiones', icon: faFutbol },
    { id: 'RESTAURANT', code: 'HAC.39', name: 'Restaurante', icon: faUtensils },
];  