export const WORLD_COUNTRIES = [
    { id: 'MX', name: 'México', code: '52', priority: 3 },
    { id: 'US', name: 'Estados Unidos', code: '1', priority: 2 },
    { id: 'CA', name: 'Canadá', code: '1', priority: 2 },
    { id: 'AR', name: 'Argentina', code: '54', priority: 2 },
    { id: 'BO', name: 'Bolivia', code: '591', priority: 2 },
    { id: 'BR', name: 'Brasil', code: '55', priority: 2 },
    { id: 'CL', name: 'Chile', code: '56', priority: 2 },
    { id: 'CO', name: 'Colombia', code: '57', priority: 2 },
    { id: 'EC', name: 'Ecuador', code: '593', priority: 2 },
    { id: 'PY', name: 'Paraguay', code: '595', priority: 2 },
    { id: 'PE', name: 'Perú', code: '51', priority: 2 },
    { id: 'UY', name: 'Uruguay', code: '598', priority: 2 },
    { id: 'VE', name: 'Venezuela', code: '58', priority: 2 },
    { id: 'CR', name: 'Costa Rica', code: '506', priority: 2 },
    { id: 'SV', name: 'El Salvador', code: '503', priority: 2 },
    { id: 'GT', name: 'Guatemala', code: '502', priority: 2 },
    { id: 'HN', name: 'Honduras', code: '504', priority: 2 },
    { id: 'NI', name: 'Nicaragua', code: '505', priority: 2 },
    { id: 'PA', name: 'Panamá', code: '507', priority: 2 },
    { id: 'CU', name: 'Cuba', code: '53', priority: 2 },
    { id: 'HT', name: 'Haití', code: '509', priority: 2 },
    { id: 'JM', name: 'Jamaica', code: '1', priority: 2 },
    { id: 'DO', name: 'República Dominicana', code: '1', priority: 2 },
    { id: 'BS', name: 'Bahamas', code: '1', priority: 2 },
    { id: 'AF', name: 'Afganistán', code: '93', priority: 1 },
    { id: 'AL', name: 'Albania', code: '355', priority: 1 },
    { id: 'DZ', name: 'Argelia', code: '213', priority: 1 },
    { id: 'AD', name: 'Andorra', code: '376', priority: 1 },
    { id: 'AO', name: 'Angola', code: '244', priority: 1 },
    { id: 'AG', name: 'Antigua y Barbuda', code: '1', priority: 1 },
    { id: 'AM', name: 'Armenia', code: '374', priority: 1 },
    { id: 'AT', name: 'Austria', code: '43', priority: 1 },
    { id: 'AZ', name: 'Azerbaiyán', code: '994', priority: 1 },
    { id: 'BH', name: 'Baréin', code: '973', priority: 1 },
    { id: 'BD', name: 'Bangladés', code: '880', priority: 1 },
    { id: 'BB', name: 'Barbados', code: '1', priority: 1 },
    { id: 'BY', name: 'Bielorrusia', code: '375', priority: 1 },
    { id: 'BE', name: 'Bélgica', code: '32', priority: 1 },
    { id: 'BZ', name: 'Belice', code: '501', priority: 1 },
    { id: 'BJ', name: 'Benín', code: '229', priority: 1 },
    { id: 'BT', name: 'Bután', code: '975', priority: 1 },
    { id: 'BA', name: 'Bosnia y Herzegovina', code: '387', priority: 1 },
    { id: 'BW', name: 'Botsuana', code: '267', priority: 1 },
    { id: 'BN', name: 'Brunéi', code: '673', priority: 1 },
    { id: 'BG', name: 'Bulgaria', code: '359', priority: 1 },
    { id: 'BF', name: 'Burkina Faso', code: '226', priority: 1 },
    { id: 'BI', name: 'Burundi', code: '257', priority: 1 },
    { id: 'KH', name: 'Camboya', code: '855', priority: 1 },
    { id: 'CM', name: 'Camerún', code: '237', priority: 1 },
    { id: 'CV', name: 'Cabo Verde', code: '238', priority: 1 },
    { id: 'TD', name: 'Chad', code: '235', priority: 1 },
    { id: 'KM', name: 'Comoras', code: '269', priority: 1 },
    { id: 'CG', name: 'Congo', code: '242', priority: 1 },
    { id: 'CD', name: 'República Democrática del Congo', code: '243', priority: 1 },
    { id: 'CK', name: 'Islas Cook', code: '682', priority: 1 },
    { id: 'CY', name: 'Chipre', code: '357', priority: 1 },
    { id: 'DK', name: 'Dinamarca', code: '45', priority: 1 },
    { id: 'DJ', name: 'Yibuti', code: '253', priority: 1 },
    { id: 'DM', name: 'Dominica', code: '1', priority: 1 },
    { id: 'EG', name: 'Egipto', code: '20', priority: 1 },
    { id: 'AE', name: 'Emiratos Árabes Unidos', code: '971', priority: 1 },
    { id: 'ER', name: 'Eritrea', code: '291', priority: 1 },
    { id: 'EE', name: 'Estonia', code: '372', priority: 1 },
    { id: 'ET', name: 'Etiopía', code: '251', priority: 1 },
    { id: 'FJ', name: 'Fiyi', code: '679', priority: 1 },
    { id: 'FI', name: 'Finlandia', code: '358', priority: 1 },
    { id: 'GA', name: 'Gabón', code: '241', priority: 1 },
    { id: 'GM', name: 'Gambia', code: '220', priority: 1 },
    { id: 'GE', name: 'Georgia', code: '995', priority: 1 },
    { id: 'GH', name: 'Ghana', code: '233', priority: 1 },
    { id: 'GR', name: 'Grecia', code: '30', priority: 1 },
    { id: 'GD', name: 'Granada', code: '1', priority: 1 },
    { id: 'GN', name: 'Guinea', code: '224', priority: 1 },
    { id: 'GW', name: 'Guinea-Bisáu', code: '245', priority: 1 },
    { id: 'GQ', name: 'Guinea Ecuatorial', code: '240', priority: 1 },
    { id: 'GY', name: 'Guyana', code: '592', priority: 1 },
    { id: 'IS', name: 'Islandia', code: '354', priority: 1 },
    { id: 'ID', name: 'Indonesia', code: '62', priority: 1 },
    { id: 'IR', name: 'Irán', code: '98', priority: 1 },
    { id: 'IQ', name: 'Irak', code: '964', priority: 1 },
    { id: 'IE', name: 'Irlanda', code: '353', priority: 1 },
    { id: 'IL', name: 'Israel', code: '972', priority: 1 },
    { id: 'JO', name: 'Jordania', code: '962', priority: 1 },
    { id: 'KZ', name: 'Kazajistán', code: '7', priority: 1 },
    { id: 'KE', name: 'Kenia', code: '254', priority: 1 },
    { id: 'KI', name: 'Kiribati', code: '686', priority: 1 },
    { id: 'KW', name: 'Kuwait', code: '965', priority: 1 },
    { id: 'KG', name: 'Kirguistán', code: '996', priority: 1 },
    { id: 'LA', name: 'Laos', code: '856', priority: 1 },
    { id: 'LV', name: 'Letonia', code: '371', priority: 1 },
    { id: 'LB', name: 'Líbano', code: '961', priority: 1 },
    { id: 'LS', name: 'Lesoto', code: '266', priority: 1 },
    { id: 'LR', name: 'Liberia', code: '231', priority: 1 },
    { id: 'LY', name: 'Libia', code: '218', priority: 1 },
    { id: 'LI', name: 'Liechtenstein', code: '423', priority: 1 },
    { id: 'LT', name: 'Lituania', code: '370', priority: 1 },
    { id: 'LU', name: 'Luxemburgo', code: '352', priority: 1 },
    { id: 'MG', name: 'Madagascar', code: '261', priority: 1 },
    { id: 'MW', name: 'Malaui', code: '265', priority: 1 },
    { id: 'MY', name: 'Malasia', code: '60', priority: 1 },
    { id: 'MV', name: 'Maldivas', code: '960', priority: 1 },
    { id: 'ML', name: 'Malí', code: '223', priority: 1 },
    { id: 'MT', name: 'Malta', code: '356', priority: 1 },
    { id: 'MH', name: 'Islas Marshall', code: '692', priority: 1 },
    { id: 'MR', name: 'Mauritania', code: '222', priority: 1 },
    { id: 'MU', name: 'Mauricio', code: '230', priority: 1 },
    { id: 'FM', name: 'Micronesia', code: '691', priority: 1 },
    { id: 'MD', name: 'Moldavia', code: '373', priority: 1 },
    { id: 'MC', name: 'Mónaco', code: '377', priority: 1 },
    { id: 'MN', name: 'Mongolia', code: '976', priority: 1 },
    { id: 'ME', name: 'Montenegro', code: '382', priority: 1 },
    { id: 'MA', name: 'Marruecos', code: '212', priority: 1 },
    { id: 'MZ', name: 'Mozambique', code: '258', priority: 1 },
    { id: 'MM', name: 'Myanmar', code: '95', priority: 1 },
    { id: 'NA', name: 'Namibia', code: '264', priority: 1 },
    { id: 'NR', name: 'Nauru', code: '674', priority: 1 },
    { id: 'NP', name: 'Nepal', code: '977', priority: 1 },
    { id: 'NL', name: 'Países Bajos', code: '31', priority: 1 },
    { id: 'NE', name: 'Níger', code: '227', priority: 1 },
    { id: 'NG', name: 'Nigeria', code: '234', priority: 1 },
    { id: 'NO', name: 'Noruega', code: '47', priority: 1 },
    { id: 'OM', name: 'Omán', code: '968', priority: 1 },
    { id: 'PK', name: 'Pakistán', code: '92', priority: 1 },
    { id: 'PW', name: 'Palaos', code: '680', priority: 1 },
    { id: 'PS', name: 'Palestina', code: '970', priority: 1 },
    { id: 'PG', name: 'Papúa Nueva Guinea', code: '675', priority: 1 },
    { id: 'PH', name: 'Filipinas', code: '63', priority: 1 },
    { id: 'PL', name: 'Polonia', code: '48', priority: 1 },
    { id: 'PT', name: 'Portugal', code: '351', priority: 1 },
    { id: 'QA', name: 'Catar', code: '974', priority: 1 },
    { id: 'RO', name: 'Rumanía', code: '40', priority: 1 },
    { id: 'RW', name: 'Ruanda', code: '250', priority: 1 },
    { id: 'WS', name: 'Samoa', code: '685', priority: 1 },
    { id: 'SM', name: 'San Marino', code: '378', priority: 1 },
    { id: 'ST', name: 'Santo Tomé y Príncipe', code: '239', priority: 1 },
    { id: 'SA', name: 'Arabia Saudita', code: '966', priority: 1 },
    { id: 'SN', name: 'Senegal', code: '221', priority: 1 },
    { id: 'RS', name: 'Serbia', code: '381', priority: 1 },
    { id: 'SC', name: 'Seychelles', code: '248', priority: 1 },
    { id: 'SL', name: 'Sierra Leona', code: '232', priority: 1 },
    { id: 'SG', name: 'Singapur', code: '65', priority: 1 },
    { id: 'SK', name: 'Eslovaquia', code: '421', priority: 1 },
    { id: 'SI', name: 'Eslovenia', code: '386', priority: 1 },
    { id: 'SB', name: 'Islas Salomón', code: '677', priority: 1 },
    { id: 'SO', name: 'Somalia', code: '252', priority: 1 },
    { id: 'KR', name: 'Corea del Sur', code: '82', priority: 1 },
    { id: 'SS', name: 'Sudán del Sur', code: '211', priority: 1 },
    { id: 'ES', name: 'España', code: '34', priority: 1 },
    { id: 'LK', name: 'Sri Lanka', code: '94', priority: 1 },
    { id: 'SD', name: 'Sudán', code: '249', priority: 1 },
    { id: 'SR', name: 'Surinam', code: '597', priority: 1 },
    { id: 'SE', name: 'Suecia', code: '46', priority: 1 },
    { id: 'CH', name: 'Suiza', code: '41', priority: 1 },
    { id: 'SY', name: 'Siria', code: '963', priority: 1 },
    { id: 'TJ', name: 'Tayikistán', code: '992', priority: 1 },
    { id: 'TZ', name: 'Tanzania', code: '255', priority: 1 },
    { id: 'TH', name: 'Tailandia', code: '66', priority: 1 },
    { id: 'TL', name: 'Timor-Leste', code: '670', priority: 1 },
    { id: 'TG', name: 'Togo', code: '228', priority: 1 },
    { id: 'TO', name: 'Tonga', code: '676', priority: 1 },
    { id: 'TT', name: 'Trinidad y Tobago', code: '1', priority: 1 },
    { id: 'TN', name: 'Túnez', code: '216', priority: 1 },
    { id: 'TR', name: 'Turquía', code: '90', priority: 1 },
    { id: 'TM', name: 'Turkmenistán', code: '993', priority: 1 },
    { id: 'TV', name: 'Tuvalu', code: '688', priority: 1 },
    { id: 'UG', name: 'Uganda', code: '256', priority: 1 },
    { id: 'UA', name: 'Ucrania', code: '380', priority: 1 },
    { id: 'AE', name: 'Emiratos Árabes Unidos', code: '971', priority: 1 },
    { id: 'GB', name: 'Reino Unido', code: '44', priority: 1 },
    { id: 'UZ', name: 'Uzbekistán', code: '998', priority: 1 },
    { id: 'VU', name: 'Vanuatu', code: '678', priority: 1 },
    { id: 'VA', name: 'Ciudad del Vaticano', code: '379', priority: 1 },
    { id: 'VN', name: 'Vietnam', code: '84', priority: 1 },
    { id: 'YE', name: 'Yemen', code: '967', priority: 1 },
    { id: 'ZM', name: 'Zambia', code: '260', priority: 1 },
    { id: 'ZW', name: 'Zimbabue', code: '263', priority: 1 }
];