import { Country } from "../types/countries.types";

export const countries: Country[] = [
    { name: "Afganistán", dialCode: "93", code: "AF" },
    { name: "Islas Åland", dialCode: "358", code: "AX" },
    { name: "Albania", dialCode: "355", code: "AL" },
    { name: "Argelia", dialCode: "213", code: "DZ" },
    { name: "Samoa Americana", dialCode: "1684", code: "AS" },
    { name: "Andorra", dialCode: "376", code: "AD" },
    { name: "Angola", dialCode: "244", code: "AO" },
    { name: "Anguila", dialCode: "1264", code: "AI" },
    { name: "Antártida", dialCode: "672", code: "AQ" },
    { name: "Antigua y Barbuda", dialCode: "1268", code: "AG" },
    { name: "Argentina", dialCode: "54", code: "AR" },
    { name: "Armenia", dialCode: "374", code: "AM" },
    { name: "Aruba", dialCode: "297", code: "AW" },
    { name: "Australia", dialCode: "61", code: "AU" },
    { name: "Austria", dialCode: "43", code: "AT" },
    { name: "Azerbaiyán", dialCode: "994", code: "AZ" },
    { name: "Bahamas", dialCode: "1242", code: "BS" },
    { name: "Baréin", dialCode: "973", code: "BH" },
    { name: "Bangladés", dialCode: "880", code: "BD" },
    { name: "Barbados", dialCode: "1246", code: "BB" },
    { name: "Bielorrusia", dialCode: "375", code: "BY" },
    { name: "Bélgica", dialCode: "32", code: "BE" },
    { name: "Belice", dialCode: "501", code: "BZ" },
    { name: "Benín", dialCode: "229", code: "BJ" },
    { name: "Bermudas", dialCode: "1441", code: "BM" },
    { name: "Bután", dialCode: "975", code: "BT" },
    { name: "Bolivia", dialCode: "591", code: "BO" },
    { name: "Bosnia y Herzegovina", dialCode: "387", code: "BA" },
    { name: "Botsuana", dialCode: "267", code: "BW" },
    { name: "Brasil", dialCode: "55", code: "BR" },
    { name: "Territorio Británico del Océano Índico", dialCode: "246", code: "IO" },
    { name: "Brunéi", dialCode: "673", code: "BN" },
    { name: "Bulgaria", dialCode: "359", code: "BG" },
    { name: "Burkina Faso", dialCode: "226", code: "BF" },
    { name: "Burundi", dialCode: "257", code: "BI" },
    { name: "Camboya", dialCode: "855", code: "KH" },
    { name: "Camerún", dialCode: "237", code: "CM" },
    { name: "Canadá", dialCode: "1", code: "CA" },
    { name: "Cabo Verde", dialCode: "238", code: "CV" },
    { name: "Islas Caimán", dialCode: "345", code: "KY" },
    { name: "República Centroafricana", dialCode: "236", code: "CF" },
    { name: "Chad", dialCode: "235", code: "TD" },
    { name: "Chile", dialCode: "56", code: "CL" },
    { name: "China", dialCode: "86", code: "CN" },
    { name: "Isla de Navidad", dialCode: "61", code: "CX" },
    { name: "Islas Cocos", dialCode: "61", code: "CC" },
    { name: "Colombia", dialCode: "57", code: "CO" },
    { name: "Comoras", dialCode: "269", code: "KM" },
    { name: "Congo", dialCode: "242", code: "CG" },
    { name: "Congo (Rep. Dem.)", dialCode: "243", code: "CD" },
    { name: "Islas Cook", dialCode: "682", code: "CK" },
    { name: "Costa Rica", dialCode: "506", code: "CR" },
    { name: "Costa de Marfil", dialCode: "225", code: "CI" },
    { name: "Croacia", dialCode: "385", code: "HR" },
    { name: "Cuba", dialCode: "53", code: "CU" },
    { name: "Chipre", dialCode: "357", code: "CY" },
    { name: "República Checa", dialCode: "420", code: "CZ" },
    { name: "Dinamarca", dialCode: "45", code: "DK" },
    { name: "Yibuti", dialCode: "253", code: "DJ" },
    { name: "Dominica", dialCode: "1767", code: "DM" },
    { name: "República Dominicana", dialCode: "1849", code: "DO" },
    { name: "Ecuador", dialCode: "593", code: "EC" },
    { name: "Egipto", dialCode: "20", code: "EG" },
    { name: "El Salvador", dialCode: "503", code: "SV" },
    { name: "Guinea Ecuatorial", dialCode: "240", code: "GQ" },
    { name: "Eritrea", dialCode: "291", code: "ER" },
    { name: "Estonia", dialCode: "372", code: "EE" },
    { name: "Etiopía", dialCode: "251", code: "ET" },
    { name: "Islas Malvinas", dialCode: "500", code: "FK" },
    { name: "Islas Faroe", dialCode: "298", code: "FO" },
    { name: "Fiyi", dialCode: "679", code: "FJ" },
    { name: "Finlandia", dialCode: "358", code: "FI" },
    { name: "Francia", dialCode: "33", code: "FR" },
    { name: "Guayana Francesa", dialCode: "594", code: "GF" },
    { name: "Polinesia Francesa", dialCode: "689", code: "PF" },
    { name: "Gabón", dialCode: "241", code: "GA" },
    { name: "Gambia", dialCode: "220", code: "GM" },
    { name: "Georgia", dialCode: "995", code: "GE" },
    { name: "Alemania", dialCode: "49", code: "DE" },
    { name: "Ghana", dialCode: "233", code: "GH" },
    { name: "Gibraltar", dialCode: "350", code: "GI" },
    { name: "Grecia", dialCode: "30", code: "GR" },
    { name: "Groenlandia", dialCode: "299", code: "GL" },
    { name: "Granada", dialCode: "1473", code: "GD" },
    { name: "Guadalupe", dialCode: "590", code: "GP" },
    { name: "Guam", dialCode: "1671", code: "GU" },
    { name: "Guatemala", dialCode: "502", code: "GT" },
    { name: "Guernesey", dialCode: "44", code: "GG" },
    { name: "Guinea", dialCode: "224", code: "GN" },
    { name: "Guinea-Bisáu", dialCode: "245", code: "GW" },
    { name: "Guyana", dialCode: "595", code: "GY" },
    { name: "Haití", dialCode: "509", code: "HT" },
    { name: "Santa Sede", dialCode: "379", code: "VA" },
    { name: "Honduras", dialCode: "504", code: "HN" },
    { name: "Hong Kong", dialCode: "852", code: "HK" },
    { name: "Hungría", dialCode: "36", code: "HU" },
    { name: "Islandia", dialCode: "354", code: "IS" },
    { name: "India", dialCode: "91", code: "IN" },
    { name: "Indonesia", dialCode: "62", code: "ID" },
    { name: "Irán", dialCode: "98", code: "IR" },
    { name: "Irak", dialCode: "964", code: "IQ" },
    { name: "Irlanda", dialCode: "353", code: "IE" },
    { name: "Isla de Man", dialCode: "44", code: "IM" },
    { name: "Israel", dialCode: "972", code: "IL" },
    { name: "Italia", dialCode: "39", code: "IT" },
    { name: "Jamaica", dialCode: "1876", code: "JM" },
    { name: "Japón", dialCode: "81", code: "JP" },
    { name: "Jersey", dialCode: "44", code: "JE" },
    { name: "Jordania", dialCode: "962", code: "JO" },
    { name: "Kazajistán", dialCode: "77", code: "KZ" },
    { name: "Kenia", dialCode: "254", code: "KE" },
    { name: "Kiribati", dialCode: "686", code: "KI" },
    { name: "Corea del Norte", dialCode: "850", code: "KP" },
    { name: "Corea del Sur", dialCode: "82", code: "KR" },
    { name: "Kuwait", dialCode: "965", code: "KW" },
    { name: "Kirguistán", dialCode: "996", code: "KG" },
    { name: "Laos", dialCode: "856", code: "LA" },
    { name: "Letonia", dialCode: "371", code: "LV" },
    { name: "Líbano", dialCode: "961", code: "LB" },
    { name: "Lesoto", dialCode: "266", code: "LS" },
    { name: "Liberia", dialCode: "231", code: "LR" },
    { name: "Libia", dialCode: "218", code: "LY" },
    { name: "Liechtenstein", dialCode: "423", code: "LI" },
    { name: "Lituania", dialCode: "370", code: "LT" },
    { name: "Luxemburgo", dialCode: "352", code: "LU" },
    { name: "Macao", dialCode: "853", code: "MO" },
    { name: "Macedonia", dialCode: "389", code: "MK" },
    { name: "Madagascar", dialCode: "261", code: "MG" },
    { name: "Malaui", dialCode: "265", code: "MW" },
    { name: "Malasia", dialCode: "60", code: "MY" },
    { name: "Maldivas", dialCode: "960", code: "MV" },
    { name: "Malí", dialCode: "223", code: "ML" },
    { name: "Malta", dialCode: "356", code: "MT" },
    { name: "Islas Marshall", dialCode: "692", code: "MH" },
    { name: "Martinica", dialCode: "596", code: "MQ" },
    { name: "Mauritania", dialCode: "222", code: "MR" },
    { name: "Mauricio", dialCode: "230", code: "MU" },
    { name: "Mayotte", dialCode: "262", code: "YT" },
    { name: "México", dialCode: "52", code: "MX" },
    { name: "Micronesia", dialCode: "691", code: "FM" },
    { name: "Moldavia", dialCode: "373", code: "MD" },
    { name: "Mónaco", dialCode: "377", code: "MC" },
    { name: "Mongolia", dialCode: "976", code: "MN" },
    { name: "Montenegro", dialCode: "382", code: "ME" },
    { name: "Montserrat", dialCode: "1664", code: "MS" },
    { name: "Marruecos", dialCode: "212", code: "MA" },
    { name: "Mozambique", dialCode: "258", code: "MZ" },
    { name: "Myanmar", dialCode: "95", code: "MM" },
    { name: "Namibia", dialCode: "264", code: "NA" },
    { name: "Nauru", dialCode: "674", code: "NR" },
    { name: "Nepal", dialCode: "977", code: "NP" },
    { name: "Países Bajos", dialCode: "31", code: "NL" },
    { name: "Antillas Neerlandesas", dialCode: "599", code: "AN" },
    { name: "Nueva Caledonia", dialCode: "687", code: "NC" },
    { name: "Nueva Zelanda", dialCode: "64", code: "NZ" },
    { name: "Nicaragua", dialCode: "505", code: "NI" },
    { name: "Níger", dialCode: "227", code: "NE" },
    { name: "Nigeria", dialCode: "234", code: "NG" },
    { name: "Niue", dialCode: "683", code: "NU" },
    { name: "Isla Norfolk", dialCode: "672", code: "NF" },
    { name: "Islas Marianas del Norte", dialCode: "1670", code: "MP" },
    { name: "Noruega", dialCode: "47", code: "NO" },
    { name: "Omán", dialCode: "968", code: "OM" },
    { name: "Pakistán", dialCode: "92", code: "PK" },
    { name: "Palau", dialCode: "680", code: "PW" },
    { name: "Territorio Palestino", dialCode: "970", code: "PS" },
    { name: "Panamá", dialCode: "507", code: "PA" },
    { name: "Papúa Nueva Guinea", dialCode: "675", code: "PG" },
    { name: "Paraguay", dialCode: "595", code: "PY" },
    { name: "Perú", dialCode: "51", code: "PE" },
    { name: "Filipinas", dialCode: "63", code: "PH" },
    { name: "Islas Pitcairn", dialCode: "872", code: "PN" },
    { name: "Polonia", dialCode: "48", code: "PL" },
    { name: "Portugal", dialCode: "351", code: "PT" },
    { name: "Puerto Rico", dialCode: "1939", code: "PR" },
    { name: "Catar", dialCode: "974", code: "QA" },
    { name: "Rumanía", dialCode: "40", code: "RO" },
    { name: "Rusia", dialCode: "7", code: "RU" },
    { name: "Ruanda", dialCode: "250", code: "RW" },
    { name: "Reunión", dialCode: "262", code: "RE" },
    { name: "San Bartolomé", dialCode: "590", code: "BL" },
    { name: "Santa Elena", dialCode: "290", code: "SH" },
    { name: "San Cristóbal y Nieves", dialCode: "1869", code: "KN" },
    { name: "Santa Lucía", dialCode: "1758", code: "LC" },
    { name: "San Martín", dialCode: "590", code: "MF" },
    { name: "San Pedro y Miquelón", dialCode: "508", code: "PM" },
    { name: "San Vicente y las Granadinas", dialCode: "1784", code: "VC" },
    { name: "Samoa", dialCode: "685", code: "WS" },
    { name: "San Marino", dialCode: "378", code: "SM" },
    { name: "Santo Tomé y Príncipe", dialCode: "239", code: "ST" },
    { name: "Arabia Saudí", dialCode: "966", code: "SA" },
    { name: "Senegal", dialCode: "221", code: "SN" },
    { name: "Serbia", dialCode: "381", code: "RS" },
    { name: "Seychelles", dialCode: "248", code: "SC" },
    { name: "Sierra Leona", dialCode: "232", code: "SL" },
    { name: "Singapur", dialCode: "65", code: "SG" },
    { name: "Eslovaquia", dialCode: "421", code: "SK" },
    { name: "Eslovenia", dialCode: "386", code: "SI" },
    { name: "Islas Salomón", dialCode: "677", code: "SB" },
    { name: "Somalia", dialCode: "252", code: "SO" },
    { name: "Sudáfrica", dialCode: "27", code: "ZA" },
    { name: "Sudán del Sur", dialCode: "211", code: "SS" },
    { name: "Georgia del Sur y las Islas Sandwich del Sur", dialCode: "500", code: "GS" },
    { name: "España", dialCode: "34", code: "ES" },
    { name: "Sri Lanka", dialCode: "94", code: "LK" },
    { name: "Sudán", dialCode: "249", code: "SD" },
    { name: "Surinam", dialCode: "597", code: "SR" },
    { name: "Svalbard y Jan Mayen", dialCode: "47", code: "SJ" },
    { name: "Suazilandia", dialCode: "268", code: "SZ" },
    { name: "Suecia", dialCode: "46", code: "SE" },
    { name: "Suiza", dialCode: "41", code: "CH" },
    { name: "Siria", dialCode: "963", code: "SY" },
    { name: "Taiwán", dialCode: "886", code: "TW" },
    { name: "Tayikistán", dialCode: "992", code: "TJ" },
    { name: "Tanzania", dialCode: "255", code: "TZ" },
    { name: "Tailandia", dialCode: "66", code: "TH" },
    { name: "Timor Oriental", dialCode: "670", code: "TL" },
    { name: "Togo", dialCode: "228", code: "TG" },
    { name: "Tokelau", dialCode: "690", code: "TK" },
    { name: "Tonga", dialCode: "676", code: "TO" },
    { name: "Trinidad y Tobago", dialCode: "1868", code: "TT" },
    { name: "Túnez", dialCode: "216", code: "TN" },
    { name: "Turquía", dialCode: "90", code: "TR" },
    { name: "Turkmenistán", dialCode: "993", code: "TM" },
    { name: "Islas Turcas y Caicos", dialCode: "1649", code: "TC" },
    { name: "Tuvalu", dialCode: "688", code: "TV" },
    { name: "Uganda", dialCode: "256", code: "UG" },
    { name: "Ucrania", dialCode: "380", code: "UA" },
    { name: "Emiratos Árabes Unidos", dialCode: "971", code: "AE" },
    { name: "Reino Unido", dialCode: "44", code: "GB" },
    { name: "Estados Unidos", dialCode: "1", code: "US" },
    { name: "Uruguay", dialCode: "598", code: "UY" },
    { name: "Uzbekistán", dialCode: "998", code: "UZ" },
    { name: "Vanuatu", dialCode: "678", code: "VU" },
    { name: "Venezuela", dialCode: "58", code: "VE" },
    { name: "Vietnam", dialCode: "84", code: "VN" },
    { name: "Islas Vírgenes Británicas", dialCode: "1284", code: "VG" },
    { name: "Islas Vírgenes de los Estados Unidos", dialCode: "1340", code: "VI" },
    { name: "Wallis y Futuna", dialCode: "681", code: "WF" },
    { name: "Yemen", dialCode: "967", code: "YE" },
    { name: "Zambia", dialCode: "260", code: "ZM" },
    { name: "Zimbabue", dialCode: "263", code: "ZW" }
];